# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: microdrop.dropbot-plugin
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}+{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    - conda-helpers >=0.4
    # .. versionchanged:: 0.19
    - dropbot >=1.37
    - flatland-fork
    - json-tricks >=3.8.0
    - microdrop >=2.0
    - microdrop-plugin-template
    - microdrop-plugin-manager >=0.14
    - microdrop-utility
    - pandas
    - path_helpers >=0.5
    - pip-helpers
    - pytables
    - pyyaml
    # .. versionchanged:: 0.16
    - wheeler.pygtkhelpers >=0.19
    - zmq-plugin

  run:
    - conda-helpers >=0.4
    # .. versionchanged:: 0.19
    - dropbot >=1.37
    - flatland-fork
    - json-tricks >=3.8.0
    - microdrop >=2.0
    - microdrop-plugin-template
    - microdrop-utility
    - pandas
    - path_helpers >=0.5
    - pip-helpers
    - pytables
    - pyyaml
    # .. versionchanged:: 0.16
    - wheeler.pygtkhelpers >=0.19
    - zmq-plugin

test:
  commands:
    - python -m mpm.bin.import_test -a {{ PKG_NAME }}

about:
  home: http://github.com/wheeler-microfluidics/dropbot-plugin
  license: BSD
