{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: microdrop.dropbot-plugin
  version: {{ GIT_VERSION }}

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    - conda-helpers >=0.4
    #: ..versionadded:: 2.38
    #:     Require `debounce.async.Debounce` for throttling capacitance UI
    #:     updates.
    - debounce >=0.3
    #: .. versionchanged:: 2.23
    #: .. versionchanged:: 2.24
    #: .. versionchanged:: 2.25
    #: .. versionchanged:: 2.26
    #: .. versionchanged:: 2.27
    #: .. versionchanged:: 2.28
    #: .. versionchanged:: 2.29
    #: .. versionchanged:: 2.32.2
    #: .. versionchanged:: 2.33
    #: .. versionchanged:: 2.37
    #: .. versionchanged:: 2.37.2
    #:     Verify that DropBot device is found before closing Teensy Loader.
    #: .. versionchanged:: 2.38
    #:     Add async DropBot monitor coroutine.
    #: .. versionchanged:: 2.38.1
    #:     Emit `'no-power'` signal from monitor if 12V not plugged.
    - dropbot >=1.68
    - flatland-fork
    - json-tricks >=3.8.0
    #: .. versionadded:: 2.27
    - logging-helpers >=0.4
    #: .. versionchanged:: 2.27
    #: .. versionchanged:: 2.33
    #:     Require `IElectrodeActuator` interface.
    #: .. versionchanged:: 2.36
    #:     Require ignorable electrode controller warning on failed actuation.
    #: .. versionchanged:: 2.37
    #:     Require updated `IPlugin` interface where `on_step_run()` is a
    #:     coroutine, accepting plugin step parameters and signals namespace as
    #:     arguments.
    #: .. versionchanged:: 2.38
    #:     Require main window status labels `gtk.HBox` container.
    #: .. versionchanged:: 2.38.7
    #:     Require `ExperimentLogController` with `get_log_path()` method.
    #: .. versionchanged:: 2.39.0
    #:     Require protocol controller with `protocol_state` attribute.
    - microdrop >=2.35
    - microdrop-plugin-template
    - microdrop-plugin-manager >=0.14
    - microdrop-utility
    #: .. versionadded:: 2.24
    - or-event
    - pandas
    - path_helpers >=0.5
    - pip-helpers
    - pytables
    - pyyaml
    #: .. versionadded:: 2.27
    - semantic_version
    #: .. versionadded:: 2.24
    - si-prefix
    #: .. versionadded:: 2.33
    - trollius
    #: .. versionchanged:: 0.16
    - wheeler.pygtkhelpers >=0.19
    - zmq-plugin

  run:
    - conda-helpers >=0.4
    #: ..versionadded:: 2.38
    #:     Require `debounce.async.Debounce` for throttling capacitance UI
    #:     updates.
    - debounce >=0.3
    #: .. versionchanged:: 2.23
    #: .. versionchanged:: 2.24
    #: .. versionchanged:: 2.25
    #: .. versionchanged:: 2.26
    #: .. versionchanged:: 2.27
    #: .. versionchanged:: 2.28
    #: .. versionchanged:: 2.29
    #: .. versionchanged:: 2.32.2
    #: .. versionchanged:: 2.33
    #: .. versionchanged:: 2.37
    #: .. versionchanged:: 2.37.2
    #:     Verify that DropBot device is found before closing Teensy Loader.
    #: .. versionchanged:: 2.38
    #:     Add async DropBot monitor coroutine.
    #: .. versionchanged:: 2.38.1
    #:     Emit `'no-power'` signal from monitor if 12V not plugged.
    - dropbot >=1.68
    - flatland-fork
    - json-tricks >=3.8.0
    #: .. versionadded:: 2.27
    - logging-helpers >=0.4
    #: .. versionchanged:: 2.27
    #: .. versionchanged:: 2.33
    #:     Require `IElectrodeActuator` interface.
    #: .. versionchanged:: 2.36
    #:     Require ignorable electrode controller warning on failed actuation.
    #: .. versionchanged:: 2.37
    #:     Require updated `IPlugin` interface where `on_step_run()` is a
    #:     coroutine, accepting plugin step parameters and signals namespace as
    #:     arguments.
    #: .. versionchanged:: 2.38
    #:     Require main window status labels `gtk.HBox` container.
    #: .. versionchanged:: 2.39.0
    #:     Require protocol controller with `protocol_state` attribute.
    - microdrop >=2.35
    - microdrop-plugin-template
    - microdrop-utility
    #: .. versionadded:: 2.24
    - or-event
    - pandas
    - path_helpers >=0.5
    - pip-helpers
    - pytables
    - pyyaml
    #: .. versionadded:: 2.27
    - semantic_version
    #: .. versionadded:: 2.24
    - si-prefix
    #: .. versionadded:: 2.33
    - trollius
    # .. versionchanged:: 0.16
    - wheeler.pygtkhelpers >=0.19
    - zmq-plugin

test:
  commands:
    - python -m mpm.bin.import_test -a {{ PKG_NAME }}

about:
  home: http://github.com/wheeler-microfluidics/dropbot-plugin
  license: BSD
