
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  path: ..

package:
  name: microdrop.dropbot-plugin
  version: 0.2

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    - conda-helpers
    - dropbot
    - json-tricks
    - microdrop_plugin_template
    - microdrop-plugin-manager >=0.8.6
    - arrow

     #TODO: we just packaged them quickly: they are alpha versions, need to take care of them
    - microdrop_helpers # this is actually microdrop, we have to fix it
    - microdrop_ext_libs

    - or-event
    - pandas
    - path-helpers
    - pytables
    - pyyaml
    - semantic_version
    - si-prefix

about:
  home: http://github.com/wheeler-microfluidics/dropbot-plugin
  license: BSD
